from srg._client import AsyncSRGClient, SRGClient
from srg.exceptions import (
    APIStatusError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    ForbiddenError,
    NotFoundError,
    ServerError,
    SRGError,
    UnprocessableEntityError,
)
from srg.schemas import (
    # workspace
    Action,
    # hub_profile
    ActionButtonLogicUpsert,
    ActionButtonResponse,
    ActionButtonUpsert,
    ActionLogicResponse,
    # asset
    AnyAssetCreate,
    AnyAssetResponse,
    Asset,
    # common
    AssetCover,
    AssetSearch,
    AssetUploadSignedUrl,
    AvailabilityLevel,
    Category,
    # channel
    CategoryHeadingContent,
    CategoryToReorder,
    CategoryWithHeadingContent,
    CategoryWithHubProfile,
    Channel,
    ChannelCategoryOptionsUpsert,
    ChannelCategoryOptionsV2,
    ChannelPrivacy,
    # content v2
    CollectionProgression,
    # content v1
    CollectionProgressionStats,
    Content,
    ContentChannelUpsert,
    ContentCover,
    ContentFileUploadParameters,
    ContentPrivacy,
    ContentProgression,
    ContentSearch,
    ContentUploadSignedUrl,
    ContentV2,
    # content widgets
    ContentWidgetCreate,
    Cover,
    CoverDetails,
    CoverOptions,
    CoverUrls,
    CreatedSection,
    CursorPagedList,
    Embed,
    EmbedAssetCreate,
    # user
    ExistsWithEmail,
    File,
    FileAssetCreate,
    FileUploadParameters,
    FullProfile,
    GetHubProfile,
    # permission
    GetPermissionGroup,
    GetTarget,
    HubProfileAvatar,
    HubProfileChannel,
    HubProfileChannelV2,
    HubProfileFilter,
    HubProfileQrCode,
    HubProfileSignedUrls,
    HubProfileWidgetCreate,
    ImageAssetCreate,
    ImageMedia,
    ImageUpsert,
    # invitation
    Invitation,
    InviteToHubWithLink,
    InviteToTarget,
    LinkListCreate,
    MainPlayableAsset,
    Media,
    MediaAssetCreate,
    MediaProgression,
    MediaWidgetCreate,
    MinimalAction,
    MinimalHubProfile,
    OrderedContentToCategoryReference,
    PermissionGroup,
    PermissionGroupUser,
    ProgressionOptions,
    ProgressionStatus,
    ProgressionUpdatedMetadata,
    PublicProfile,
    Seat,
    Section,
    SectionBaseCreate,
    SignedUrl,
    SRGModel,
    SubscriptionDetails,
    TextWidgetCreate,
    UserFullProfile,
    Video,
    VideoAssetCreate,
    ViewOptions,
    Workspace,
    WorkspaceSignedUrl,
    WorkspaceUser,
    WorkspaceUserProfile,
    WorkspaceUserRole,
    # pagination
    async_paginate,
    paginate,
    parse_asset_response,
)

__all__ = [
    # clients
    "SRGClient",
    "AsyncSRGClient",
    # exceptions
    "SRGError",
    "APIStatusError",
    "BadRequestError",
    "AuthenticationError",
    "ForbiddenError",
    "NotFoundError",
    "ConflictError",
    "UnprocessableEntityError",
    "ServerError",
    # common models
    "SRGModel",
    "SignedUrl",
    "CoverDetails",
    "Cover",
    "CoverUrls",
    "AssetCover",
    "ContentCover",
    "CursorPagedList",
    "ImageUpsert",
    "FileUploadParameters",
    "ContentFileUploadParameters",
    # pagination helpers
    "paginate",
    "async_paginate",
    # literal types
    "ContentPrivacy",
    "ChannelPrivacy",
    "AvailabilityLevel",
    "ProgressionStatus",
    # user models
    "UserFullProfile",
    "PublicProfile",
    "FullProfile",
    "ExistsWithEmail",
    # invitation models
    "InviteToTarget",
    "InviteToHubWithLink",
    "Invitation",
    # permission models
    "GetTarget",
    "WorkspaceUser",
    "WorkspaceUserRole",
    "WorkspaceUserProfile",
    "PermissionGroup",
    "PermissionGroupUser",
    "GetPermissionGroup",
    # hub profile models
    "ActionButtonLogicUpsert",
    "ActionButtonUpsert",
    "ActionLogicResponse",
    "ActionButtonResponse",
    "HubProfileQrCode",
    "GetHubProfile",
    "HubProfileAvatar",
    "HubProfileFilter",
    "MinimalHubProfile",
    "HubProfileSignedUrls",
    # workspace models
    "Workspace",
    "Seat",
    "SubscriptionDetails",
    "WorkspaceSignedUrl",
    "ProgressionUpdatedMetadata",
    "Action",
    "MinimalAction",
    # asset models
    "Asset",
    "Media",
    "Embed",
    "File",
    "Video",
    "ImageMedia",
    "AnyAssetResponse",
    "parse_asset_response",
    "AssetSearch",
    "AssetUploadSignedUrl",
    "MediaAssetCreate",
    "EmbedAssetCreate",
    "FileAssetCreate",
    "ImageAssetCreate",
    "VideoAssetCreate",
    "AnyAssetCreate",
    # channel v1 models
    "ChannelCategoryOptionsUpsert",
    "CategoryToReorder",
    "SectionBaseCreate",
    "Channel",
    "HubProfileChannel",
    "Category",
    "Section",
    "OrderedContentToCategoryReference",
    # channel v2 models
    "HubProfileChannelV2",
    "CategoryWithHubProfile",
    "CategoryWithHeadingContent",
    "CategoryHeadingContent",
    "ChannelCategoryOptionsV2",
    "ProgressionOptions",
    "ViewOptions",
    "CoverOptions",
    # content widget models
    "TextWidgetCreate",
    "MediaWidgetCreate",
    "LinkListCreate",
    "HubProfileWidgetCreate",
    "ContentWidgetCreate",
    # content v1 models
    "ContentChannelUpsert",
    "Content",
    "ContentSearch",
    "ContentUploadSignedUrl",
    "ContentProgression",
    "CollectionProgressionStats",
    # content v2 models
    "ContentV2",
    "CreatedSection",
    "MainPlayableAsset",
    "MediaProgression",
    "CollectionProgression",
]

__version__ = "0.2.0"
